### ISSUE TITLE
大腿有做一下性能测试嘛

### ISSUE THREAD

**Issue by shuyabin** [FireLustre/php-dfa-sensitive#1]
大腿有做一下性能测试嘛,api使用挺简单的.

**Comment by FireLustre** [comment]
目前只做了词库量的性能测试，词库量在1w+左右应该也没什么问题

**Comment by Kim1am** [comment]
大腿，为什么我运行到
$filterContent = SensitiveHelper::init(); 
会直接退出程序？

**Comment by FireLustre** [comment]
具体有报什么错误吗
