### ISSUE TITLE
敏感词汇匹配问题

### ISSUE THREAD

**Issue by im-zhangxi** [FireLustre/php-dfa-sensitive#18]
这种装修风格还是不错的。我们的家就是这么装修的？
这样一句话

`       $wordFilePath = base_path().'\sensitive\keywords.txt';
        $handle = SensitiveHelper::init()->setTreeByFile($wordFilePath);
        $filterContent = $handle->replace('这种装修风格还是不错的。我们的家就是这么装修的', '*', true);`
替换成的结果 居然是: 
     这种装修风格还是不错*。我们*家就是这么装修*
为什么把的这个字匹配到了把？  我这句话  没有问题的

**Comment by FireLustre** [comment]
检查一下`keywords.txt`中是否把`的`作为了敏感词

**Comment by im-zhangxi** [comment]
@FireLustre  这应该是我的问题。虽然我没有在keywords.txt 找到的敏感词，但是当我更换了词库以后，就不在出现这个问题。 非常感谢
