### ISSUE TITLE
检测敏感词，会出现同一个敏感词匹配多次。

### ISSUE THREAD

**Issue by jiangwu10057** [FireLustre/php-dfa-sensitive#24]
语句：

> 视频内容：20世纪初，人们发现了一种比细菌还要小的病原体：病毒。病毒由蛋白质外壳和遗传物质组成，必须寄生在细胞里才能表现出生命特征。病毒可以一次次欺骗细胞，最终将自己的遗传物质送到寄主细胞核里。病毒可以在细胞中潜伏很久，在某个时刻突然爆发，寄主就会死亡。人们已经发现了七种冠状病毒，其中有三种可以引起严重疾病，即SARS、MERS和新型冠状病毒，它们都会引起免疫系统的强烈反应，产生细胞因子风暴，大量的白细胞和组织液充斥肺部，造成呼吸困难和死亡。免疫反应既不能太弱，也不能太强，平衡的免疫力才是最好的免疫力。面对病毒，人们的反应与免疫系统一样，毫不在意或者过分恐慌都是不对的，平静的等一段时间，疫情一定会被消灭。

”病毒“是敏感词，那么getBadWord将返回的列表将出现5次病毒。

我的处理方式是在SensitiveHelper的getBadWord方法中将
`
$badWordList[] = mb_substr($content, $length, $matchFlag, 'utf-8');
`
修改为
`
$badWord = mb_substr($content, $length, $matchFlag, 'utf-8');

if(!in_array($badWord, $badWordList)){
       $badWordList[] = $badWord;
}
`
或者
在返回的时候array_unique去重！

**Comment by FireLustre** [comment]
非常感谢你提出的这个问题，同时欢迎你提交pr
