### ISSUE TITLE
mark 方法有问题

### ISSUE THREAD

**Issue by gaoyong06** [FireLustre/php-dfa-sensitive#27]
`

       // 获取感词库索引数组
        $wordData = array(
            '傻逼',
            '狗',
            '麻痹',
            '尼玛',
        );

        $content = "我擦，——————————你麻痹的——————，尼玛的，你个傻逼尼玛的，你个傻逼尼玛的，你个傻逼尼玛的，你个傻逼尼玛的你个傻逼尼玛的，你个傻逼";

        $filterContent = SensitiveHelper::init()->setTree($wordData)->mark($content, '<mark>', '</mark>');

        var_dump($filterContent);

`

替换后结果是：

`
我擦，——————————你<mark>麻痹</mark>的——————，<mark><mark><mark><mark><mark><mark>尼玛</mark></mark></mark></mark></mark></mark>的，你个<mark><mark><mark><mark><mark><mark>傻逼</mark></mark></mark></mark></mark></mark><mark><mark><mark><mark><mark><mark>尼玛</mark></mark></mark></mark></mark></mark>的，你个<mark><mark><mark><mark><mark><mark>傻逼</mark></mark></mark></mark></mark></mark><mark><mark><mark><mark><mark><mark>尼玛</mark></mark></mark></mark></mark></mark>的，你个<mark><mark><mark><mark><mark><mark>傻逼</mark></mark></mark></mark></mark></mark><mark><mark><mark><mark><mark><mark>尼玛</mark></mark></mark></mark></mark></mark>的，你个<mark><mark><mark><mark><mark><mark>傻逼</mark></mark></mark></mark></mark></mark><mark><mark><mark><mark><mark><mark>尼玛</mark></mark></mark></mark></mark></mark>的你个<mark><mark><mark><mark><mark><mark>傻逼</mark></mark></mark></mark></mark></mark><mark><mark><mark><mark><mark><mark>尼玛</mark></mark></mark></mark></mark></mark>的，你个<mark><mark><mark><mark><mark><mark>傻逼</mark></mark></mark></mark></mark></mark>
`

上面的 <mark></mark>很多在重复

**Comment by gaoyong06** [comment]
找到问题了：

作者在 DfaFilter\SensitiveHelper.php，第231行增加一行

array_unique($badWordList);

就可以了，在只在mark方法内部去了重复，不影响其他的逻辑

**Comment by FireLustre** [comment]
Thanks your issue. Fixed.
