### ISSUE TITLE
composer 安装出现以下问题，不成功。

### ISSUE THREAD

**Issue by fuduoluo** [FireLustre/php-dfa-sensitive#28]
安装报错如下： 
Problem 1
    - The requested package minimum-stability could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package phpmailer/phpmailer (installed at v5.2.27, required as ~6.0.6) is satisfiable by phpmailer/phpmailer[v5.2.27] but these conflict with your requirements or minimum-stability.

**Comment by PaulCnth** [comment]
错误提示信息很明确了。
1 - 用的稳定版本，使用 dev，或者某个版本标签；
2 - 指定 phpmailer 的版本号，使其可以兼容。

tips:
故障信息不嫌其多，贴的越仔细，找到问题的概率越高。

happy coding :_)

**Comment by PaulCnth** [comment]
仔细看 readme 文档，发现已经把这个报警提示信息的解决办法写进去了。
