### ISSUE TITLE
过滤英文字符 如何使用

### ISSUE THREAD

**Issue by kayw-geek** [FireLustre/php-dfa-sensitive#30]
假如我的词库中设置的 hell 为敏感词，但是 我输入了 hello 也会别替换称****o,还是说这个算法不支持英文

**Comment by GabyCheng** [comment]
> 假如我的词库中设置的 hell 为敏感词，但是 我输入了 hello 也会别替换称****o,还是说这个算法不支持英文

我也想问，应该是不支持，你最后怎么解决的。我看到一个扩展
