### ISSUE TITLE
只获取一个敏感词问题

### ISSUE THREAD

**Issue by Smilefish2** [FireLustre/php-dfa-sensitive#6]
```php
// 仅且获取一个敏感词
$sensitiveWordGroup = $handle->getBadWord($content, 1);

```

这个功能无效，尝试修改 public function getBadWord($content, $matchType = 0) ，并增加判断位置后实现了功能：
```php
$badWordList[] = mb_substr($content, $length, $matchFlag, 'utf-8');
 // 只匹配1个
if (1 === $matchType)  {
    break;
}
```
我去提交个PR。。。

**Comment by FireLustre** [comment]
首先关于方法`getBadWord`的第二个参数`$matchType`的注释问题说声抱歉，`matchType`应该为算法的最小匹配维度，其次是我这边通过添加了参数`$wordNum`,支持了返回规定数量的限制。最后感谢你提的PR。Thanks!

**Comment by Smilefish2** [comment]
后来想了想感觉不对，就把PR关了，还是你的解决靠谱[点赞]，感谢啊[抱拳]

**Comment by Smilefish2** [comment]
Thanks Thanks Thanks
